apiVersion: v1
kind: Service
metadata:
  name: ferretdb
  namespace: cnpg-system
  labels:
    app: ferretdb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${COMP_HOSTNAME}.${DOMAIN}
spec:
  type: LoadBalancer
  selector:
    app: ferretdb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
